name: Release
on: workflow_dispatch
jobs:
  Windows:
    runs-on: windows-latest
    permissions:
        contents: write
        actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null --quiet
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.2
          haxelib install flixel 5.2.2
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.10.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxvlc 1.2.0
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit.git
          haxelib install hscript 2.5.0
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git extension-androidtools https://github.com/Default-name123/oldtools.git
          haxelib install hxcpp-debug-server
          haxelib list

      - name: Building
        run: haxelib run lime build windows

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: WindowsBuild
          path: export/release/windows/bin/
          if-no-files-found: warn
