
# THE FOLLOWING ACTIONS CODE IS FROM THE PSYCH ENGINE REPO: https://github.com/ShadowMario/FNF-PsychEngine/blob/main/.github/workflows/main.yml

name: windows

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ReleaseBuild:
    runs-on: windows-latest
    permissions:
        contents: write
        actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.2
          haxelib install flixel 5.2.2
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.10.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxvlc 1.2.0
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit.git
          haxelib install hscript 2.5.0
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib install hxvlc 1.2.0
          haxelib install hxcpp-debug-server
          haxelib list

      - name: Building
        run: haxelib run lime build windows

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ReleaseBuild
          path: export/release/windows/bin
